### ISSUE TITLE
OUnit does not work with pyml

### ISSUE THREAD

**Issue by zajer** [gildor478/ounit#15]
I am unable to to test my code that uses the pyml library.
For example if one of my unit-test files looks like:
```
open OUnit2

let test_1 _ = 
    let _ = Py.initialize ~version:3 ()
    in
      ()
let suite =
  "My tests" >::: [
    "My test 1">:: test_1
]

let () =
  run_test_tt_main suite

```
and the dune file responsible for launching the test is as follows:
```
(
    tests
    (names 
        example_tests
    ) 
    (modes native )    
    (libraries pyml ounit2 )
)
```
If I try to run the above test I get an exception. The output is attached as a text file.
[test_results.txt](https://github.com/gildor478/ounit/files/4345419/test_results.txt)

I would like to point out that running the above test without a usage of the OUnit works perfectly fine:
```
let test_1 _ = 
    let _ = Py.initialize ~version:3 ()
    in
      ()
let suite =
  test_1 ()

```

**Comment by gildor478** [comment]
Py.initialize modifies the environment variables, this is something that should be done outside of the test, because this could cause race condition or hidden dependency in the test suite.
http://xunitpatterns.com/Erratic%20Test.html#Interacting%20Tests

You should just move the "let () = Py.initialize ..." outside of the test so that the initialization is done once and for all tests.

The relevant output in the results:
```
Check that the environment variables haven't changed during the test.

differences:
+PYTHONHOME=/lib/x86_64-linux-gnu/..,
+PYTHONPATH=:/usr/lib/python37.zip:/u[...]/python3/dist-packages
```

**Comment by zajer** [comment]
Thank you, this indeed solves the issue.
